name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    #runs-on: ubuntu:focal-20210921

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
           PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           HOSTNAME: ${{ secrets.HOST_DNS }}
           USER_NAME: ${{ secrets.USERNAME }}
           TARGET: ${{ secrets.TARGET_DIR }}                 
        
        run: |
           command -v ssh-agent >/dev/null || apt-get update && apt-get install -y openssh-client openssh-server
           eval $(ssh-agent -s)
           echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
           #mkdir ~/.ssh
           #echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
           #chmod 600 ~/.ssh/id_rsa
           #echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
           #ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 
              #sudo apt-get -y update
              #sudo apt-get install -y apache2
              #sudo systemctl start apache2
              #sudo systemctl enable apache2
              #cd home
              #sudo mv * /var/www/html
