name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04

    steps:
      - uses: appleboy/ssh-action@v0.1.10
      #- uses: actions/checkout@v2
      #- name: Build & Deploy
      #  env:
      #     PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     HOSTNAME: ${{ secrets.HOST_DNS }}
      #     USER_NAME: ${{ secrets.USERNAME }}
      #     TARGET: ${{ secrets.TARGET_DIR }}                 
        
      #  run: |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 
      #        #sudo apt-get -y update
      #        #sudo apt-get install -y apache2
      #        #sudo systemctl start apache2
      #        #sudo systemctl enable apache2
      #        #cd home
              #sudo mv * /var/www/html
